name: xqflite
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
    
  sqflite: ^2.3.3
  sqflite_common_ffi:
  collection: 
  cuid2: ^3.1.0
  uuid: ^4.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0

  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
